apiVersion: v1
kind: Service
metadata:
  name: '{{.Values.c-service.serviceName}}'
spec:
  selector:
    app: '{{.Values.c-service.serviceName}}'
  ports:
  - name: http
    port: 80
    targetPort: '{{.Values.c-service.containerPort}}'
  type: ClusterIP
