apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{.Values.c-service.serviceName}}'
  labels:
    app: '{{.Values.c-service.serviceName}}'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local
